export const images = {
  logo: {
    dark: require('./logo/dark.svg'),
    light: require('./logo/light.svg'),
  },
  mode: {
    dark: {
      daytime: require('./mode/dark/daytime.svg'),
      nighttime: require('./mode/dark/nighttime.svg'),
    },
    light: {
      daytime: require('./mode/light/daytime.svg'),
      nighttime: require('./mode/light/nighttime.svg'),
    },
  },
  misc: {
    play: require('./misc/play.svg'),
    error: require('./misc/error.svg'),
    menuLight: require('./misc/menuLight.svg'),
    menuDark: require('./misc/menuDark.svg'),
    close: require('./misc/close.svg'),
    outlink: require('./misc/outlink.svg'),
    commentDark: require('./misc/commentDark.svg'),
    commentLight: require('./misc/commentLight.svg'),
    seemoreDark: require('./misc/seemoreDark.svg'),
    seemoreLight: require('./misc/seemoreLight.svg'),
    symbolDark: require('./misc/symbolDark.svg'),
    symbolLight: require('./misc/symbolLight.svg'),
    shareDark: require('./misc/shareDark.svg'),
    shareLight: require('./misc/shareLight.svg'),
    music: require('./misc/music.svg'),
    warning: require('./misc/warning.svg'),
  },
  arrow: {
    backDark: require('./arrow/backDark.svg'),
    backLight: require('./arrow/backLight.svg'),
    crossDark: require('./arrow/crossDark.svg'),
    crossLight: require('./arrow/crossLight.svg'),
    downDark: require('./arrow/downDark.svg'),
    downLight: require('./arrow/downLight.svg'),
    moreDark: require('./arrow/moreDark.svg'),
    moreLight: require('./arrow/moreLight.svg'),
  },
  services: {
    githubLight: require('./services/githubLight.svg'),
    postypeLight: require('./services/postypeLight.svg'),
    develogLight: require('./services/develogLight.svg'),
    velogLight: require('./services/velogLight.svg'),
    dev1studioLight: require('./services/dev1studioLight.svg'),
    githubDark: require('./services/githubDark.svg'),
    postypeDark: require('./services/postypeDark.svg'),
    develogDark: require('./services/develogDark.svg'),
    velogDark: require('./services/velogDark.svg'),
    dev1studioDark: require('./services/dev1studioDark.svg'),
    studioDark: require('./services/studioDark.svg'),
    studioLight: require('./services/studioLight.svg'),
  },
  home: {
    downloadDefaultBefore: require('./home/download-default-before.svg'),
    downloadDefaultAfter: require('./home/download-default-after.svg'),
    downloadHoverBefore: require('./home/download-hover-before.svg'),
    downloadHoverAfter: require('./home/download-hover-after.svg'),
    primary: require('./home/primary.svg'),
    secondary: require('./home/secondary.svg'),
  },
  slide: {
    nextLight: require('./slide/nextLight.svg'),
    pauseLight: require('./slide/pauseLight.svg'),
    playLight: require('./slide/playLight.svg'),
    prevLight: require('./slide/prevLight.svg'),
    nextDark: require('./slide/nextDark.svg'),
    pauseDark: require('./slide/pauseDark.svg'),
    playDark: require('./slide/playDark.svg'),
    prevDark: require('./slide/prevDark.svg'),
  },
  tab: {
    playlist: {
      active: require('./tab/playlist/active.svg'),
      dark: require('./tab/playlist/dark.svg'),
      light: require('./tab/playlist/light.svg'),
      defaultDark: require('./tab/playlist/defaultDark.svg'),
      defaultLight: require('./tab/playlist/defaultLight.svg'),
    },
    interview: {
      active: require('./tab/interview/active.svg'),
      dark: require('./tab/interview/dark.svg'),
      light: require('./tab/interview/light.svg'),
      defaultDark: require('./tab/interview/defaultDark.svg'),
      defaultLight: require('./tab/interview/defaultLight.svg'),
    },
    newsic: {
      active: require('./tab/newsic/active.svg'),
      dark: require('./tab/newsic/dark.svg'),
      light: require('./tab/newsic/light.svg'),
      defaultDark: require('./tab/newsic/defaultDark.svg'),
      defaultLight: require('./tab/newsic/defaultLight.svg'),
    },
  },
};
